title: "San Magdalena"
description: "A setting bible for my worldbuilding project."
baseurl: "/Obsidian-Vaults" 
url: "https://dan-willborromeo.github.io" 

theme: minima  

# Markdown processing settings
markdown: kramdown
permalink: pretty  # Ensures URLs are clean (no .html in links)

# Plugins for better functionality
plugins:
  - jekyll-feed       # RSS feed generation
  - jekyll-seo-tag    # Better SEO metadata
  - jekyll-sitemap    # Auto-generates a sitemap.xml

# Defaults to apply to all pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

# Fix internal linking issues (for Jekyll pages)
relative_permalinks: false

# Exclude unnecessary files from the build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - _notes/ 
  - .obsidian/  

github:
  is_project_page: true
